/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_future0923_debug_tools_vm_VmTool */

#ifndef _Included_io_github_future0923_debug_tools_vm_VmTool
#define _Included_io_github_future0923_debug_tools_vm_VmTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_future0923_debug_tools_vm_VmTool
 * Method:    forceGc0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_future0923_debug_tools_vm_VmTool_forceGc0
  (JNIEnv *, jclass);

/*
 * Class:     io_github_future0923_debug_tools_vm_VmTool
 * Method:    getInstances0
 * Signature: (Ljava/lang/Class;I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_io_github_future0923_debug_tools_vm_VmTool_getInstances0
  (JNIEnv *, jclass, jclass, jint);

/*
 * Class:     io_github_future0923_debug_tools_vm_VmTool
 * Method:    sumInstanceSize0
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_future0923_debug_tools_vm_VmTool_sumInstanceSize0
  (JNIEnv *, jclass, jclass);

/*
 * Class:     io_github_future0923_debug_tools_vm_VmTool
 * Method:    getInstanceSize0
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_future0923_debug_tools_vm_VmTool_getInstanceSize0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_future0923_debug_tools_vm_VmTool
 * Method:    countInstances0
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_future0923_debug_tools_vm_VmTool_countInstances0
  (JNIEnv *, jclass, jclass);

/*
 * Class:     io_github_future0923_debug_tools_vm_VmTool
 * Method:    getAllLoadedClasses0
 * Signature: (Ljava/lang/Class;)[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_io_github_future0923_debug_tools_vm_VmTool_getAllLoadedClasses0
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
